#!/usr/bin/env python3
"""gen-logos.py — render the TC8 boot-selector icons from PNG sources.

Two modes:
  preview:  gen-logos.py SRC_DIR OUT_DIR [VERSION] [ICON_SCALE] [LABEL_PT] [ROTATE]
              upright PNGs + a contact sheet, for style review.
  embed:    gen-logos.py --embed SRC_DIR LOGOS_DIR HEADER [VERSION]
              24bpp BMPs (spun 90deg CCW for the panel) + a regenerated
              tc8_logos.h. Meant to run at build time.

The option art is stored 90deg CCW; it's spun CW to upright, labelled (DejaVu
Sans Mono, light drop shadow, centered under the glyph), then the whole composite
is spun CCW so it lands upright on the rotated TC8 panel. The submarine keeps its
art + a "BOOTLOADER <ver>" stamp.
"""
import sys, os
from PIL import Image, ImageDraw, ImageFont

SIZE = 256
BG = (0, 0, 0)
INK = (238, 238, 238)
SHADOW = (0, 0, 0)
FONT = "/usr/share/fonts/truetype/dejavu/DejaVuSansMono-Bold.ttf"
SCALE = 0.78          # option glyph size (fraction of frame)
LABEL_PT = 14
PANEL_CCW = 270       # bake spin: 270 -> ROTATE_90 -> 90deg CCW for the panel

# (source png, label | None for the submarine, array/bmp name, key_bg, unrotate)
JOBS = [
    ("submarine.png", None,           "ublogo",      None,            True),
    ("emmc.png",      "BOOT LINUX",   "m2_emmc",     None,            True),
    ("net.png",       "NETWORK BOOT", "m3_net",      None,            True),
    ("drive.png",     "INSTALL",      "m4_fastboot", None,            True),
    ("sdp.png",       "RECOVERY",     "m5_sdp",      (255, 255, 255), True),
]


def key_bg(im, color, thresh=30):
    im = im.convert("RGBA")
    px = im.load()
    for y in range(im.height):
        for x in range(im.width):
            r, g, b, a = px[x, y]
            if abs(r - color[0]) < thresh and abs(g - color[1]) < thresh and abs(b - color[2]) < thresh:
                px[x, y] = (r, g, b, 0)
    return im


def label(draw, text, font, cx, top, dx=1, dy=1):
    b = draw.textbbox((0, 0), text, font=font)
    x = cx - (b[2] - b[0]) // 2
    draw.text((x + dx, top + dy), text, font=font, fill=SHADOW)
    draw.text((x, top), text, font=font, fill=INK)


def render(src, lab, key, unrotate, scale, label_pt, version, rotate=0):
    c = Image.new("RGB", (SIZE, SIZE), BG)
    d = ImageDraw.Draw(c)
    ic = Image.open(src).convert("RGBA")
    if unrotate:
        ic = ic.transpose(Image.ROTATE_270)   # 90deg CW: art is stored CCW
    if key:
        ic = key_bg(ic, key)
    f = ImageFont.truetype(FONT, label_pt)
    if lab is None:                                   # submarine: big + version stamp
        g = int(SIZE * 0.70)
        ic = ic.resize((g, g), Image.LANCZOS)
        c.paste(ic, ((SIZE - g) // 2, int(SIZE * 0.04)), ic)
        label(d, version, f, SIZE // 2, SIZE - label_pt - 14)
    else:                                             # option: big glyph + small label
        g = int(SIZE * scale)
        ic = ic.resize((g, g), Image.LANCZOS)
        c.paste(ic, ((SIZE - g) // 2, int(SIZE * 0.02)), ic)
        label(d, lab, f, SIZE // 2, SIZE - label_pt - 14)
    if rotate == 90:
        c = c.transpose(Image.ROTATE_270)
    elif rotate == 180:
        c = c.transpose(Image.ROTATE_180)
    elif rotate == 270:
        c = c.transpose(Image.ROTATE_90)              # 90deg CCW (panel)
    return c


def preview(src_dir, out_dir, version, scale, label_pt, rotate):
    os.makedirs(out_dir, exist_ok=True)
    imgs = []
    for src, lab, name, key, unrotate in JOBS:
        img = render(os.path.join(src_dir, src), lab, key, unrotate, scale, label_pt, version, rotate)
        img.save(os.path.join(out_dir, name + ".png"))
        imgs.append(img)
    sheet = Image.new("RGB", (SIZE * len(imgs), SIZE), (24, 24, 24))
    for i, im in enumerate(imgs):
        sheet.paste(im, (i * SIZE, 0))
    sheet.save(os.path.join(out_dir, "_sheet.png"))
    print("preview ->", out_dir)


def embed(src_dir, logos_dir, header, version):
    os.makedirs(logos_dir, exist_ok=True)
    arrays = []
    for src, lab, name, key, unrotate in JOBS:
        img = render(os.path.join(src_dir, src), lab, key, unrotate, SCALE, LABEL_PT, version, PANEL_CCW)
        bmp = os.path.join(logos_dir, name + ".bmp")
        img.save(bmp)                                 # 24bpp BMP
        data = open(bmp, "rb").read()
        arrays.append((name + "_bmp", data))
        print(f"  {name}.bmp  {len(data)} B")
    with open(header, "w") as h:
        h.write("/* Auto-generated by scripts/gen-logos.py --embed from logos/src/*.png.\n"
                " * 256x256 24bpp BMPs: option art un-rotated, mono-labelled, then the whole\n"
                " * composite spun 90deg CCW for the rotated TC8 panel. Do not hand-edit. */\n")
        h.write("#ifndef TC8_LOGOS_H\n#define TC8_LOGOS_H\n")
        for name, data in arrays:
            h.write(f"static const unsigned char {name}[] = {{\n")
            for i in range(0, len(data), 12):
                h.write("  " + ", ".join(f"0x{b:02x}" for b in data[i:i + 12]) + ",\n")
            h.write("};\n")
            h.write(f"static const unsigned int {name}_len = {len(data)};\n")
        h.write("#endif\n")
    print("wrote", header)


def main(argv):
    if len(argv) > 1 and argv[1] == "--embed":
        src_dir, logos_dir, header = argv[2], argv[3], argv[4]
        version = argv[5] if len(argv) > 5 else "BOOTLOADER v0.4"
        embed(src_dir, logos_dir, header, version)
    else:
        src_dir, out_dir = argv[1], argv[2]
        version = argv[3] if len(argv) > 3 else "BOOTLOADER v0.4"
        scale = float(argv[4]) if len(argv) > 4 else SCALE
        label_pt = int(argv[5]) if len(argv) > 5 else LABEL_PT
        rotate = int(argv[6]) if len(argv) > 6 else 0
        preview(src_dir, out_dir, version, scale, label_pt, rotate)


if __name__ == "__main__":
    main(sys.argv)
